name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le projet
        uses: actions/checkout@v4

      - name: Installer Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Installer Android SDK 36
        run: |
          yes | sdkmanager --licenses > /dev/null || true
          sdkmanager "platforms;android-36"

      - name: Installer Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.13'

      - name: Ouvrir le nouveau projet
        run: |
          rm -rf android-project
          mkdir android-project
          unzip -q "PHARMACOPEE_KENEYASO_SOURCE_TEST_100_FAIDA_30_DEDICACES.zip" -d android-project

      - name: Construire APK
        run: |
          PROJECT_DIR="$(dirname "$(find android-project -type f \( -name 'settings.gradle.kts' -o -name 'settings.gradle' \) | head -n 1)")"
          echo "Projet Android : $PROJECT_DIR"
          cd "$PROJECT_DIR"
          gradle :app:assembleDebug --stacktrace

      - name: Publier APK
        uses: actions/upload-artifact@v4
        with:
          name: PHARMACOPEE-KENEYASO-APK
          path: android-project/**/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
